# Generated by Django 5.0.3 on 2024-03-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('template_type', models.CharField(choices=[('ProductDevelopmentTemplate', 'ProductDevelopmentTemplate')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDevelopmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(max_length=500)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmatic_pages.keyword')),
            ],
        ),
    ]
