# Generated by Django 5.0.3 on 2024-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0002_alter_productdevelopmenttemplate_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdevelopmenttemplate',
            name='meta_description',
            field=models.TextField(max_length=160),
        ),
    ]
