# Generated by Django 5.0.3 on 2024-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0003_alter_productdevelopmenttemplate_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
