# Generated by Django 5.0.3 on 2024-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0005_productdevelopmenttemplate_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='second_title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
