# Generated by Django 5.0.3 on 2024-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0006_productdevelopmenttemplate_second_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='second_intro',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
