# Generated by Django 5.0.3 on 2024-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0007_productdevelopmenttemplate_second_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='idea_generation_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
