# Generated by Django 5.0.3 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0008_productdevelopmenttemplate_idea_generation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdevelopmenttemplate',
            name='idea_generation_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
