# Generated by Django 5.0.3 on 2024-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0009_alter_productdevelopmenttemplate_idea_generation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='validation_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
