# Generated by Django 5.0.3 on 2024-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0010_productdevelopmenttemplate_validation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdevelopmenttemplate',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
