# Generated by Django 5.0.3 on 2024-03-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0011_alter_productdevelopmenttemplate_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='prototyping_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
