# Generated by Django 5.0.3 on 2024-03-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0012_productdevelopmenttemplate_prototyping_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='marketing_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
