# Generated by Django 5.0.3 on 2024-03-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0013_productdevelopmenttemplate_marketing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='evaluating_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='launch_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
