# Generated by Django 5.0.3 on 2024-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0014_productdevelopmenttemplate_evaluating_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestionProductDevelopmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=300, null=True)),
                ('answer', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productdevelopmenttemplate',
            name='faq',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='programmatic_pages.faqquestionproductdevelopmenttemplate'),
        ),
    ]
