# Generated by Django 5.0.3 on 2024-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0015_faqquestionproductdevelopmenttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestionproductdevelopmenttemplate',
            name='answer',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='faqquestionproductdevelopmenttemplate',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
