# Generated by Django 5.0.3 on 2024-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0016_alter_faqquestionproductdevelopmenttemplate_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdevelopmenttemplate',
            name='faq',
            field=models.ManyToManyField(blank=True, null=True, to='programmatic_pages.faqquestionproductdevelopmenttemplate'),
        ),
    ]
