# Generated by Django 5.0.3 on 2024-03-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmatic_pages', '0017_alter_productdevelopmenttemplate_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdevelopmenttemplate',
            name='faq',
        ),
        migrations.AddField(
            model_name='faqquestionproductdevelopmenttemplate',
            name='product_development_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programmatic_pages.productdevelopmenttemplate'),
        ),
    ]
