version: "2.2"
services:

  app:
    build: 
      context: .
    volumes:
      - static:/static
      - .:/django   
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: gunicorn product_launch_site.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file: 
      - .env

  nginx-proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - app
    volumes:
      - static:/static

      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  


volumes:
  static:
  certs:
  html:
  vhost:
  acme: