# Generated by Django 5.0.3 on 2024-03-10 18:34

import blog.models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=blog.models.default_date_time, verbose_name='Post date')),
                ('intro', wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='blog_images/title')),
                ('second_intro', wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('secondary_title', models.CharField(max_length=300)),
                ('secondary_title_image', models.ImageField(blank=True, null=True, upload_to='blog_images/secondary')),
                ('text_before_content', wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('content', wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(required=False))]))])),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
